
INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Sentimos que toda satisfa��o de nossos desejos advinda do mundo assemelha -se � esmola que mant�m hoje o mendigo vivo, por�m prolonga amanh� a sua fome. A resigna��o, ao contr�rio, assemelha -se � fortuna herdada: livra o herdeiro para sempre de todas as preocupa��es.SCHOPENHAUER, A. Aforismo para a sabedoria da vida. S�o Paulo: Martins Fontes, 2005.O  trecho  destaca  uma  ideia  remanescente  de  umaWUDGLomR ORVyFD RFLGHQWDO  VHJXQGR D TXDO D IHOLFLGDGH  se mostra indissociavelmente ligada �','OFICIAL','A consagra��o de relacionamentos afetivos. ','B administra��o da independ�ncia interior. ','C fugacidade do conhecimento emp�rico.','D liberdade de express�o religiosa. ','E busca de prazeres ef�meros.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Batizado por Tancredo Neves de "Nova Rep�blica", o per�odo que marca o reencontro do Brasil com os governos civis e a democracia ainda n�o completou seu quinto ano e j� viveu dias de grande como��o. Come�ou com a trag�dia de Tancredo, seguiu pela euforia do Plano Cruzado, conheceu as depress�es daLQ�DomR H GDV DPHDoDV GD KLSHULQ�DomR H GHVHPERFRX  na movimenta��o que antecede as primeiras elei��es diretas para presidente em 29 anos.O �lbum dos presidentes: a hist�ria vista pelo JB. Jornal do Brasil, 15 nov. 1989.O per�odo descrito apresenta continuidades e rupturas em rela��o � conjuntura hist�rica anterior. Uma dessas continuidades consistiu na','OFICIAL','A representa��o do legislativo com a f�rmula do bipartidarismo.','B deten��o de lideran�as populares por crimes de subvers�o.','C presen�a de pol�ticos com trajet�rias no regime autorit�rio.','D prorroga��o das restri��es advindas dos atos institucionais.','E estabilidade da economia com o congelamento anual de pre�os.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Os moradores de Andalsnes, na Noruega, poderiam se dar ao luxo de morar perto do trabalho nos dias �teis eGH VH UHIXJLDU QD FDOPDULD GR ERVTXH DRV �QV GH VHPDQD  E sem sair da mesma casa. Bastaria achar uma vaga para estacionar o im�vel antes de curtir o novo endere�o.Dispon�vel em: http://casavogue.globo.com. Acesso em: 3 out. 2015 (adaptado).Uma vez implementada, essa proposta afetaria a din�mica do espa�o urbano por reduzir a intensidade do seguinte processo:','OFICIAL','A �xodo rural.','B Movimento pendular. ','C Migra��o de retorno. ','D Deslocamento sazonal.','E Ocupa��o de �reas centrais.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O Rio de Janeiro tem proje��o imediata no pr�prio estado e no Esp�rito Santo, em parcela do sul do estado da Bahia, e na Zona da Mata, em Minas Gerais, ondetem influencia divida com Belo Horizonte. Comp�ema rede urbana do Rio de Janeiro, entre outras cidades: Vit�ria, Juiz de Fora, Cachoeiro de Itapemirim, Campos dos Goytacazes, Volta Redonda - Barra Mansa, Teixeira de Freitas, Angra dos Reis e Teres�polis.Dispon�vel em: http://ibge.gov.br. Acesso em: 9 jul. 2015 (adaptado).O conceito que expressa a rela��o entre o espa�o apresentado e a cidade do Rio de Janeiro �:','OFICIAL','A	Frente pioneira. ','B Zona de transi��o.','C Regi�o polarizada.','D �rea de conurba��o.','E Periferia metropolitana.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','TEXTO I   Documentos do s�culo XVI algumas vezes se referem aos habitantes ind�genas como "os brasis", ou "gente bras�lia" e, ocasionalmente no s�culo XVII, o termo "brasileiro" era a eles aplicado, mas as refer�ncias ao status econ�mico e jur�dico desses eram muito mais populares. Assim, os termos "negro da terra" e "�ndios" eram utilizados com mais frequ�ncia do que qualquer outro.SCHWARTZ, S. B. Gente da terra braziliense da na��o. Pensando o Brasil: a constru��o deum povo. In: MOTA, C. G. (Org.). Viagem incompleta: a experi�ncia brasileira (1500-2000).S�o Paulo: Senac, 2000 (adaptado).TEXTO II   �ndio � um conceito constru�do no processo de conquista da Am�rica pelos europeus. Desinteressados pela diversidade cultural, imbu�dos de forte preconceito para com o outro, o indiv�duo de outras culturas, espanh�is, portugueses, franceses e anglo-sax�es terminaram por denominar da mesma forma povos t�o d�spares quanto os tupinamb�s e os astecas.SILVA, K. V.; SILVA, M. H. Dicion�rio de conceitos hist�ricos. S�o Paulo: Contexto, 2005.Ao comparar os textos, as formas de designa��o dos grupos nativos pelos europeus, durante o per�odo analisado, s�o reveladoras da','OFICIAL','A	concep��o idealizada do territ�rio, entendido comoJHRJUD�FDPHQWH LQGLIHUHQFLDGR ','B	percep��o corrente de uma ancestralidade comum �s popula��es amer�ndias.','C	compreens�o etnoc�ntrica acerca das popula��es dos territ�rios conquistados.','D	transposi��o direta das categorias originadas no imagin�rio medieval.','E	YLVmR  XWySLFD  FRQ�JXUDGD  D  SDUWLU  GH  IDQWDVLDV  GH  riqueza.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Ser ou n�o ser - eis a $QUEST�O.Morrer - dormir - Dormir! Talvez sonhar. A� est� o obst�culo! Os sonhos que h�o de vir no sono da morteQuando tivermos escapado ao tumulto vital 1RV REULJDP D KHVLWDU  H p HVVD D UH�H[mR Que d� � desventura uma vida t�o longa.SHAKESPEARE, W. Hamlet. Porto Alegre: L&PM, 2007.Este solil�quio pode ser considerado um precursor do existencialismo ao enfatizar a tens�o entre','OFICIAL','A consci�ncia de si e ang�stia humana.','B inevitabilidade do destino e incerteza moral.','C tragicidade da personagem e ordem do mundo. ','D racionalidade argumentativa e loucura iminente. ','E depend�ncia paterna e impossibilidade de a��o.|A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','TEXTO ITradu��o: "As mulheres do futuro far�o da Lua um lugar mais limpo para se viver".Dispon�vel em: www.propagandashistoricas.com.br. Acesso em: 16 out. 2015.TEXTO IIMetade da nova equipe da Nasa� composta por mulheres   At� hoje, cerca de 350 astronautas americanos j� estiveram no espa�o, enquanto as mulheres n�o chegam a ser um ter�o desse n�mero. Ap�s o an�ncio da turma composta 50% por mulheres, alguns internautas escreveram coment�rios machistas e desrespeitosos sobre a escolha nas redes sociais.Dispon�vel em: https://catracalivre.com.br. Acesso em: 10 mar. 2016.A compara��o entre o an�ncio publicit�rio de 1968 e a repercuss�o da not�cia de 2016 mostra a','OFICIAL','A HOLWL]DomR GD FDUUHLUD FLHQWt�FD ','B TXDOL�FDomR GD DWLYLGDGH GRPpVWLFD ','C ambi��o de ind�strias patrocinadoras. ','D manuten��o de estere�tipos de g�nero.','E equipara��o de pap�is nas rela��es familiares.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A �frica Ocidental � conhecida pela din�mica das suas mulheres comerciantes, caracterizadas pela per�cia, autonomia e mobilidade. A sua presen�a, que fora atestada por viajantes e por mission�rios portugueses que visitaram a costa a partir do s�culo XV, consta tamb�m na ampla documenta��o sobre a regi�o. A literatura � rica em refer�ncias �s grandes mulheres como as vendedoras ambulantes, cujo jeito para o neg�cio, bem como a autonomia e mobilidade, � t�o t�pico da regi�o.HAVIK, P. Din�micas e assimetrias afro-atl�nticas: a ag�ncia feminina e representa��es emmudan�a na Guin� (s�culos XIX e XX). In: PANTOJA, S. (Org.). Identidades, mem�rias ehist�rias em terras africanas. Bras�lia: LGE; Luanda: Nzila, 2006.A abordagem realizada pelo autor sobre a vida social da �frica Ocidental pode ser relacionada a uma caracter�stica marcante das cidades no Brasil escravista nos s�culos XVIII e XIX, que se observa pela','OFICIAL','A restri��o � realiza��o do com�rcio ambulante por africanos escravizados e seus descendentes.','B conviv�ncia entre homens e mulheres livres, de diversas origens, no pequeno com�rcio.','C presen�a de mulheres negras no com�rcio de rua de diversos produtos e alimentos.','D dissolu��o dos h�bitos culturais trazidos do continente de origem dos escravizados.','E entrada de imigrantes portugueses nas atividades ligadas ao pequeno com�rcio urbano.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Quanto mais complicada se tornou a produ��o industrial, mais numerosos passaram a ser os elementos da ind�stria que exigiam garantia de fornecimento. Tr�s deles eram de import�ncia fundamental: o trabalho, a terra e o dinheiro. Numa sociedade comercial, esse fornecimento s� poderia ser organizado de uma forma: tornando-os dispon�veis � compra. Agora eles tinham que ser organizados para a venda no mercado. Isso estava de acordo com a exig�ncia de um sistema de mercado. Sabemos que em um sistema como esse, os lucros s� podem ser assegurados se se garante a autorregula��o por meio de mercados competitivos interdependentes.POLANYI, K. A grande transforma��o: as origens de nossa �poca.Rio de Janeiro: Campus, 2000 (adaptado).A consequ�ncia do processo de transforma��o socioecon�mica abordado no texto � a','OFICIAL','A expans�o das terras comunais.','B limita��o do mercado como meio de especula��o. ','C consolida��o da for�a de trabalho como mercadoria.','D diminui��o do com�rcio como efeito da industrializa��o.','E adequa��o do dinheiro como elemento padr�o das transa��es.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O que ocorreu na Bahia de 1798, ao contr�rio das outras situa��es de contesta��o pol�tica na Am�rica portuguesa, � que o projeto que lhe era subjacente n�o tocou somente na condi��o, ou no instrumento, da integra��o subordinada das col�nias no imp�rio luso. Dessa feita, ao contr�rio do que se deu nas Minas Gerais (1789), a sedi��o avan�ou sobre a sua decorr�ncia.JANCS�, I.; PIMENTA, J. P. Pe�as de um mosaico. In: MOTA, C. G. (Org.). Viagem incompleta:a experi�ncia brasileira (1500-2000). S�o Paulo: Senac, 2000.A diferen�a entre as sedi��es abordadas no texto encontrava-se na pretens�o de','OFICIAL','A eliminar a hierarquia militar.','B abolir a escravid�o africana.','C anular o dom�nio metropolitano. ','D suprimir a propriedade fundi�ria.','E extinguir o absolutismo mon�rquico.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','TEXTO IDispon�vel em: http://portal.iphan.gov.br. Acesso em: 6 abr. 2016.TEXTO II    A elei��o dos novos bens, ou melhor, de novas formas de se conceber a condi��o do patrim�nio cultural nacional, tamb�m permite que diferentes grupos sociais, utilizando as leis do Estado e o apoio de especialistas, revejam as imagens e alegorias do seu passado, do queTXHUHP JXDUGDU H GH�QLU FRPR SUySULR H LGHQWLWiULR ABREU, M.; SOIHET, R.; GONTIJO, R. (Org.). Cultura pol�tica e leituras do passado: KLVWRULRJUD�D H HQVLQR GH KLVWyULD. Rio de Janeiro: Civiliza��o Brasileira, 2007.O texto chama a aten��o para a import�ncia da prote��o de bens que, como aquele apresentado na imagem, seLGHQWL�FDP FRPR ','OFICIAL','A	Artefatos sagrados.','B Heran�as materiais. ','C Objetos arqueol�gicos. ','D Pe�as comercializ�veis.','E Conhecimentos tradicionais.|E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','No in�cio de maio de 2014, a instala��o da plataforma petrol�fera de perfura��o HYSY-981 nas �guas contestadas do Mar da China Meridional suscitou especula��es sobre as motiva��es chinesas. Na avalia��o de diversos observadores ocidentais, Pequim pretendeu, com esse gesto, demonstrar que pode impor seu controle e dissuadir outros pa�ses de seguir com suas reivindica��es de direito de explora��o dessas �guas, como � o caso do Vietn� e das Filipinas.KLARE, M.T. A guerra pelo petr�leo se joga no mar. Le Monde Diplomatique Brasil, abr. 2015.A a��o da China em rela��o � situa��o descrita no texto HYLGHQFLD XP FRQ�LWR TXH WHP FRPR IRFR R D','OFICIAL','A	Distribui��o das zonas econ�micas especiais.','B Monop�lio das inova��es tecnol�gicas extrativas. ','C Dinamiza��o da atividade comercial.','D Jurisdi��o da soberania territorial. ','E Embargo da produ��o industrial.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A Opera��o Condor est� diretamente vinculada �s experi�ncias hist�ricas das ditaduras civil-militares que se disseminaram pelo Cone Sul entre as d�cadas de 1960 e 1980. Depois do Brasil (e do Paraguai de Stroessner), foi a vez da Argentina (1966), Bol�via (1966 e 1971), Uruguai e Chile (1973) e Argentina (novamente, em 1976). Em todos os casos se instalaram ditaduras civil-militares (em menor ou maior medida) com base na Doutrina de Seguran�a Nacional e tendo como principais caracter�sticas um anticomunismo militante, a identifica��o do inimigo interno, a imposi��o do papel pol�tico das For�as Armadas e a defini��o de fronteiras ideol�gicas.PADR�S, E. S. et al. Ditadura de Seguran�a Nacional no Rio Grande do Sul (1964-1985):hist�ria e mem�ria. Porto Alegre: Corag, 2009 (adaptado).Levando-se em conta o contexto em que foi criada, a referida opera��o tinha como objetivo coordenar a','OFICIAL','A	PRGL�FDomR GH OLPLWHV WHUULWRULDLV  ','B VREUHYLYrQFLD GH R�FLDLV H[LODGRV ','C interfer�ncia de pot�ncias mundiais. ','D repress�o de ativistas oposicionistas. ','E implanta��o de governos nacionalistas.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A regula��o das rela��es de trabalho comp�e uma estrutura complexa, em que cada elemento se ajusta aos demais. A Justi�a do Trabalho � apenas uma das pe�as dessa vasta engrenagem. A presen�a de representantes classistas na composi��o dos �rg�os da Justi�a do Trabalho � tamb�m resultante da montagem dessaUHJXODomR   2  SRGHU  QRUPDWLYR  WDPEpP  UH�HWH  HVVD  caracter�stica. Institu�da pela Constitui��o de 1934, a Justi�a do Trabalho s� vicejou no ambiente pol�tico do Estado Novo instaurado em 1937.ROMITA, A. S. Justi�a do Trabalho: produto do Estado Novo. In: PANDOLFI, D. (Org.).Repensando o Estado Novo. Rio de Janeiro: Editora FGV, 1999.A cria��o da referida institui��o estatal na conjuntura hist�rica abordada teve por objetivo','OFICIAL','A	legitimar os protestos fabris.','B RUGHQDU RV FRQ�LWRV ODERUDLV  ','C R�FLDOL]DU RV VLQGLFDWRV SOXUDLV ','D assegurar os princ�pios liberais.','E XQL�FDU RV VDOiULRV SUR�VVLRQDLV|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','3DUFHULD 7UDQVSDFt�FDCanad�Estados UnidosJap�oVietn�M�xicoCingapuraBrunei DarussalamMal�siaPeruAustr�liaChileNova Zel�ndia  Dispon�vel em: http://portuguese.brazil.usembassy.gov. Acesso em: 11 maio 2016 (adaptado).Dentro das atuais redes produtivas, o referido bloco apresenta composi��o estrat�gica por se tratar de um conjunto de pa�ses com','OFICIAL','A	elevado padr�o social.','B	sistema monet�rio integrado.','C	alto desenvolvimento tecnol�gico. ','D identidades culturais semelhantes.','E vantagens locacionais complementares.|E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Segundo a Confer�ncia de Quioto, os pa�ses centrais industrializados, respons�veis hist�ricos pela polui��o, deveriam alcan�ar a meta de redu��o de 5,2% do total de emiss�es segundo n�veis de 1990. O n� da $QUEST�O � o enorme custo desse processo, demandando mudan�as radicais nas ind�strias para que se adaptem rapidamente aos limites de emiss�o estabelecidos e adotem tecnologias energ�ticas limpas. A comercializa��o internacional de cr�ditos de sequestro ou de redu��o de gases causadores do efeito estufa foi a solu��o encontrada para reduzir o custo global do processo. Pa�ses ou empresas que conseguirem reduzir as emiss�es abaixo de suas metas poder�o vender este cr�dito para outro pa�s ou empresa que n�o consiga.BECKER, B. Amaz�nia: geopol�tica na virada do II mil�nio. Rio de Janeiro: Garamond, 2009.As posi��es contr�rias � estrat�gia de compensa��o presente no texto relacionam-se � ideia de que ela promove','OFICIAL','A	retra��o nos atuais n�veis de consumo.','B	VXUJLPHQWR GH FRQ�LWRV GH FDUiWHU GLSORPiWLFR ','C diminui��o dos lucros na produ��o de energia.','D desigualdade na distribui��o do impacto ecol�gico.','E	decr�scimo dos �ndices de desenvolvimento econ�mico.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Dados recentes mostram que muitos s�o os pa�ses perif�ricos que dependem dos recursos enviados pelos imigrantes que est�o nos pa�ses centrais. Grande parte dos pa�ses da Am�rica Latina, por exemplo, depende hoje das remessas de seus imigrantes. Para se ter uma ideia mais concreta, recentes dados divulgados pela ONU revelaram que somente os indianos recebem 10 bilh�es de d�lares de seus compatriotas no exterior. No M�xico, segundo maior volume de divisas, esse valor chega a 9,9 bilh�es de d�lares e nas Filipinas, o terceiro, a 8,4 bilh�es.HAESBAERT, R.; PORTO-GON�ALVES, C. W. A nova des-ordem mundial.S�o Paulo: Edunesp, 2006.Um aspecto do mundo globalizado que facilitou a ocorr�ncia do processo descrito, na transi��o do s�culo XX para o s�culo XXI, foi o(a)','OFICIAL','A	integra��o de culturas distintas. ','B avan�o t�cnico das comunica��es. ','C quebra de barreiras alfandeg�rias.','D �H[LELOL]DomR GH UHJUDV WUDEDOKLVWDV ','E desconcentra��o espacial da produ��o.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Nunca nos tornaremos matem�ticos, por exemplo, embora nossa mem�ria possua todas as demonstra��es feitas por outros, se nosso esp�rito n�o for capaz de resolver toda esp�cie de problemas; n�o nos tornar�amos �OyVRIRV   SRU  WHU  OLGR  WRGRV  RV  UDFLRFtQLRV  GH  3ODWmR  H  Arist�teles, sem poder formular um ju�zo s�lido sobre o que nos � proposto. Assim, de fato, parecer�amos ter aprendido, n�o ci�ncias, mas hist�rias.DESCARTES, R. Regras para a orienta��o do esp�rito. S�o Paulo: Martins Fontes, 1999.Em sua busca pelo saber verdadeiro, o autor considera o conhecimento, de modo cr�tico, como resultado da','OFICIAL','A	investiga��o de natureza emp�rica. ','B retomada da tradi��o intelectual. ','C imposi��o de valores ortodoxos. ','D autonomia do sujeito pensante.','E liberdade do agente moral.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0',' Pois quem seria t�o in�til ou indolente a ponto de n�o desejar saber como e sob que esp�cie de constitui��o os romanos conseguiram em menos de cinquenta e tr�s anos submeter quase todo o mundo habitado ao seu governo exclusivo - fato nunca antes ocorrido? Ou, em outras palavras, quem seria t�o apaixonadamente devotado a outros espet�culos ou estudos a ponto de considerar qualquer outro objetivo mais importante que a aquisi��o desse conhecimento?POL�BIO. Hist�ria. Bras�lia: Editora UnB, 1985.A experi�ncia a que se refere o historiador Pol�bio, nesse texto escrito no s�culo II a.C., � a','OFICIAL','A	amplia��o do contingente de camponeses livres. ','B consolida��o do poder das falanges hoplitas.','C concretiza��o do des�gnio imperialista. ','D ado��o do monote�smo crist�o.','E liberta��o do dom�nio etrusco.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','SATRAPI, M. Pers�polis. S�o Paulo: Cia. das Letras, 2007 (adaptado).A mem�ria recuperada pela autora apresenta a rela��o entre','OFICIAL','A	FRQ�LWR WUDEDOKLVWD H HQJDMDPHQWR VLQGLFDO ','B organiza��o familiar e prote��o � inf�ncia. ','C centraliza��o econ�mica e prega��o religiosa. ','D estrutura educacional e desigualdade de renda.','E WUDQVIRUPDomR SROtWLFD H PRGL�FDomR GH FRVWXPHV |E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','TEXTO I   Fragmento B91: N�o se pode banhar duas vezes no mesmo rio, nem subst�ncia mortal alcan�ar duas vezes a mesma condi��o; mas pela intensidade e rapidez da mudan�a, dispersa e de novo re�ne.HER�CLITO. Fragmentos (Sobre a natureza). S�o Paulo: Abril Cultural, 1996 (adaptado).TEXTO IIFragmento B8: S�o muitos os sinais de que o ser�	ing�nito e indestrut�vel, pois � compacto, inabal�velH  VHP  �P-  QmR  IRL  QHP  VHUi   SRLV  p  DJRUD  XP  WRGR  homog�neo, uno, cont�nuo. Como poderia o que � perecer? Como poderia gerar-se?PARM�NIDES. Da natureza. S�o Paulo: Loyola, 2002 (adaptado).Os fragmentos do pensamento pr�-socr�tico exp�em uma oposi��o que se insere no campo das','OFICIAL','A	investiga��es do pensamento sistem�tico. ','B preocupa��es do per�odo mitol�gico.','C discuss�es de base ontol�gica. ','D habilidades da ret�rica sof�stica. ','E verdades do mundo sens�vel.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','GHPRFUDFLD  GHOLEHUDWLYD  D�UPD  TXH  DV  SDUWHV GR  FRQ�LWR  SROtWLFR  GHYHP  GHOLEHUDU  HQWUH  VL  H   SRU  meio de argumenta��o razo�vel, tentar chegar a um acordo sobre as pol�ticas que seja satisfat�rio paraWRGRV  $ GHPRFUDFLD DWLYLVWD GHVFRQ�D GDV H[RUWDo}HV �	delibera��o por acreditar que, no mundo real daSROtWLFD   RQGH  DV  GHVLJXDOGDGHV  HVWUXWXUDLV  LQ�XHQFLDP  procedimentos e resultados, processos democr�ticos que parecem cumprir as normas de delibera��oJHUDOPHQWH  WHQGHP  D  EHQH�FLDU  RV  DJHQWHV  PDLV  poderosos. Ela recomenda, portanto, que aqueles que se preocupam com a promo��o de mais justi�a devem realizar principalmente a atividade de oposi��o cr�tica, em vez de tentar chegar a um acordo com quem sustentaHVWUXWXUDV GH SRGHU H[LVWHQWHV RX GHODV VH EHQH�FLD <281*  ,  0  HVD�RV DWLYLVWDV j GHPRFUDFLD GHOLEHUDWLYD  Revista Brasileira de Ci�ncia Pol�tica, n. 13, jan.-abr. 2014.As concep��es de democracia deliberativa e de democracia ativista apresentadas no texto tratam como imprescind�veis, respectivamente,','OFICIAL','A	a decis�o da maioria e a uniformiza��o de direitos. ','B a organiza��o de elei��es e o movimento anarquista. ','C a obten��o do consenso e a mobiliza��o das minorias. ','D a fragmenta��o da participa��o e a desobedi�ncia civil.','E	a imposi��o de resist�ncia e o monitoramento da liberdade.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A promessa da tecnologia moderna se converteu em uma amea�a, ou esta se associou �quela de forma indissol�vel. Ela vai al�m da constata��o da amea�a f�sica. Concebida para a felicidade humana, a submiss�o da natureza, na sobremedida de seu sucesso, que agora se estende � pr�pria natureza do homem, conduziuDR  PDLRU  GHVD�R  Mi  SRVWR  DR  VHU  KXPDQR  SHOD  VXD pr�pria a��o. O novo continente da pr�xis coletiva que adentramos com a alta tecnologia ainda constitui, para a teoria �tica, uma terra de ningu�m.JONAS, H. O princ�pio da responsabilidade. Rio de Janeiro:Contraponto; Editora PUC-Rio, 2011 (adaptado).As implica��es �ticas da articula��o apresentada no texto impulsionam a necessidade de constru��o de um novo padr�o de comportamento, cujo objetivo consiste em garantir o(a)','OFICIAL','A	pragmatismo da escolha individual. ','B sobreviv�ncia de gera��es futuras. ','C fortalecimento de pol�ticas liberais. ','D valoriza��o de m�ltiplas etnias.','E promo��o da inclus�o social.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','TEXTO IImagem de S�o Benedito. Dispon�vel em: http://acervo.bndigital.bn.br.Acesso em: 6 jan. 2016 (adaptado).TEXTO II    Os santos tornaram-se grandes aliados da Igreja para atrair novos devotos, pois eram obedientes a Deus e ao poder clerical. Contando e estimulando o conhecimentoVREUH D YLGD GRV VDQWRV  D ,JUHMD WUDQVPLWLD DRV �pLV RV ensinamentos que julgava corretos e que deviam ser imitados por escravos que, em geral, traziam outras cren�as de suas terras de origem, muito diferentes das que preconizava a f� cat�lica.OLIVEIRA, A. J. Negra devo��o. Revista de Hist�ria da Biblioteca Nacional, n. 20, maio 2007 (adaptado).3RVWHULRUPHQWH  UHVVLJQL�FDGRV  QR  LQWHULRU  GH  FHUWDV  irmandades e no contato com outra matriz religiosa, o �cone e a pr�tica mencionada no texto estiveram desde o s�culo XVII relacionados a um esfor�o da Igreja Cat�lica para','OFICIAL','A	reduzir o poder das confrarias.','B	cristianizar a popula��o afro-brasileira. ','C espoliar recursos materiais dos cativos.','D recrutar libertos para seu corpo eclesi�stico.','E atender a demanda popular por padroeiros locais.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Em 1935, o governo brasileiro come�ou a negar vistos a judeus. Posteriormente, durante o Estado Novo, uma circular secreta proibiu a concess�o de vistos a "pessoas de origem semita", inclusive turistas e negociantes, o que causou uma queda de 75% da imigra��o judaica ao longo daquele ano. Entretanto, mesmo com as imposi��es da lei, muitos judeus continuaram entrando ilegalmente no pa�s durante a guerra e as amea�as de deporta��o em massa nunca foram concretizadas, apesar da extradi��o de alguns indiv�duos por sua milit�ncia pol�tica.GRIMBERG, K. Nova l�ngua interior: 500 anos de hist�ria dos judeus no Brasil. In: IBGE.Brasil: 500 anos de povoamento. Rio de Janeiro: IBGE, 2000 (adaptado).Uma raz�o para a ado��o da pol�tica de imigra��o mencionada no texto foi o(a)','OFICIAL','A	receio do controle sionista sobre a economia nacional.','B	reserva de postos de trabalho para a m�o de obra local.','C	oposi��o do clero cat�lico � expans�o de novas religi�es.','D	apoio da diplomacia varguista �s opini�es dos l�deres �rabes.','E	simpatia de membros da burocracia pelo projeto totalit�rio alem�o.|E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','3LUUR  D�UPDYD  TXH  QDGD  p  QREUH  QHP  YHUJRQKRVR   justo ou injusto; e que, da mesma maneira, nada existe do ponto de vista da verdade; que os homens agem apenas segundo a lei e o costume, nada sendo mais isto do que aquilo. Ele levou uma vida de acordo com esta doutrina, nada procurando evitar e n�o se desviando do que quer que fosse, suportando tudo, carro�as, por exemplo, precip�cios, c�es, nada deixando ao arb�trio dos sentidos.LA�RCIO, D. 9LGDV H VHQWHQoDV GRV �OyVRIRV LOXVWUHV. Bras�lia: Editora UnB, 1988.O ceticismo, conforme sugerido no texto, caracteriza-se por:','OFICIAL','A	Desprezar quaisquer conven��es e obriga��es da sociedade.','B	Atingir o verdadeiro prazer como o princ�pio e o fim da vida feliz.','C	Defender a indiferen�a e a impossibilidade de obter alguma certeza.','D	Aceitar o determinismo e ocupar-se com a esperan�a transcendente.','E	$JLU GH IRUPD YLUWXRVD H ViELD D �P GH HQDOWHFHU R  homem bom e belo.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O conceito de fun��o social da cidade incorpora a organiza��o do espa�o f�sico como fruto da regula��o social, isto �, a cidade deve contemplar todos os seus moradores e n�o somente aqueles que est�o no mercado formal da produ��o capitalista da cidade. A tradi��o dosFyGLJRV GH HGL�FDomR  XVR H RFXSDomR GR VROR QR %UDVLO  sempre partiram do pressuposto de que a cidade n�o tem divis�es entre os inclu�dos e os exclu�dos socialmente.QUINTO JR., L. P. Nova legisla��o urbana e os velhos fantasmas.Estudos Avan�ados (USP), n. 47, 2003 (adaptado).Uma pol�tica governamental que contribui para viabilizar a fun��o social da cidade, nos moldes indicados no texto, � a','OFICIAL','A TXDOL�FDomR   GH   VHUYLoRV   S~EOLFRV   HP   EDLUURV perif�ricos.','B	implanta��o de centros comerciais em eixos rodovi�rios.','C	proibi��o de constru��es residenciais em regi�es �ngremes.','D	dissemina��o de equipamentos culturais em locais tur�sticos.','E desregulamenta��o do setor imobili�rio em �reas favelizadas.|A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O bioma Cerrado foi considerado recentemente um dos 25 hotspots de biodiversidade do mundo, segundo uma an�lise em escala mundial das regi�esELRJHRJUi�FDV  VREUH  iUHDV  JOREDLV  SULRULWiULDV  SDUD  conserva��o. O conceito de hotspot foi criado tendo em vista a escassez de recursos direcionados para conserva��o, com o objetivo de apresentar os chamados "pontos quentes", ou seja, locais para os quais existe maior necessidade de direcionamento de esfor�os, buscando evitar a extin��o de muitas esp�cies que est�o altamente amea�adas por a��es antr�picas.PINTO, P. P.; DINIZ-FILHO, J. A. F. In: ALMEIDA, M. G. (Org.). Tantos cerrados: m�ltiplas abordagens sobre a biogeodiversidade e singularidade cultural. Goi�nia: Vieira, 2005 (adaptado).A necessidade desse tipo de a��o na �rea mencionada tem como causa a','OFICIAL','A	LQWHQVL�FDomR GD DWLYLGDGH WXUtVWLFD ','B implanta��o de parques ecol�gicos. ','C explora��o dos recursos minerais. ','D eleva��o do extrativismo vegetal. ','E expans�o da fronteira agr�cola.|E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','TEXTO I    Mais de 50 mil refugiados entraram no territ�rio h�ngaro apenas no primeiro semestre de 2015. Budapeste lan�ou os "trabalhos preparat�rios" para a constru��o de um muro de quatro metros de altura e 175 km ao longo de sua fronteira com a S�rvia, informou o ministro h�ngaro das Rela��es Exteriores. "UmaUHVSRVWD  FRPXP  GD  8QLmR  (XURSHLD  D  HVWH  GHVD�R  GD imigra��o � muito demorada, e a Hungria n�o podeHVSHUDU  7HPRV TXH DJLU�  MXVWL�FRX R PLQLVWUR LVSRQtYHO HP  ZZZ SRUWXJXHV U� IU  $FHVVR HP     MXQ        DGDSWDGR TEXTO II   O Alto Comissariado das Na��es Unidas para Refugiados (ACNUR) critica as manifesta��es de xenofobia adotadas pelo governo da Hungria. O pa�s foi invadido por cartazes nos quais o chefe do executivo insta os imigrantes a respeitarem as leis e a n�o "roubarem" os empregos dos h�ngaros. Para o ACNUR, a medida � surpreendente, pois a xenofobia costuma ser instigada por pequenos grupos radicais e n�o pelo pr�prio governo do pa�s.Dispon�vel em: http://pt.euronews.com. Acesso em: 19 jun. 2015 (adaptado).O posicionamento governamental citado nos textos � criticado pelo ACNUR por ser considerado um caminho para o(a)','OFICIAL','A	altera��o do regime pol�tico.','B	fragiliza��o da supremacia nacional.','C H[SDQVmR GRV GRPtQLRV JHRJUi�FRV ','D cerceamento da liberdade de express�o.','E fortalecimento das pr�ticas de discrimina��o.|E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A  sociologia  ainda  n�o  ultrapassou  a  era  dasFRQVWUXo}HV  H  GDV  VtQWHVHV  �ORVy�FDV   (P  YH]  GH  assumir a tarefa de lan�ar luz sobre uma parcela restrita do campo social, ela prefere buscar as brilhantes generalidades em que todas as quest�es s�o levantadas sem que nenhuma seja expressamente tratada. N�o � com exames sum�rios e por meio de intui��es r�pidas que se pode chegar a descobrir as leis de uma realidade t�o complexa. Sobretudo, generaliza��es �s vezes t�o amplas e t�o apressadas n�o s�o suscet�veis de nenhum tipo de prova.DURKHEIM, E. O suic�dio: estudo de sociologia. S�o Paulo: Martins Fontes, 2000.O texto expressa o esfor�o de �mile Durkheim em construir uma sociologia com base na','OFICIAL','A	YLQFXODomR FRP D �ORVR�D FRPR VDEHU XQL�FDGR ','B	reuni�o de percep��es intuitivas para demonstra��o.','C	formula��o de hip�teses subjetivas sobre a vida social.','D	ades�o aos padr�es de investiga��o t�picos das ci�ncias naturais.','E	incorpora��o de um conhecimento alimentado pelo engajamento pol�tico.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','','OFICIAL','A	concentra��o fundi�ria, impedindo os negros de tomar posse leg�tima do uso da terra.','B	boicote econ�mico, proibindo os negros de consumir produtos ingleses sem resist�ncia armada.','C	sincretismo religioso, vetando os ritos sagrados dos QHJURV QDV FHULP{QLDV R�FLDLV GR (VWDGR ','D	controle sobre a movimenta��o, desautorizando os negros a transitar em determinadas �reas das cidades.','E	exclus�o do mercado de trabalho, negando � popula��o negra o acesso aos bens de consumo.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A linhagem dos primeiros cr�ticos ambientais brasileiros n�o praticou o elogio laudat�rio da beleza e da grandeza do meio natural brasileiro. O meio natural foi elogiado por sua riqueza e potencial econ�mico, sendo sua destrui��o interpretada como um signo de atraso, ignor�ncia e falta de cuidado.P�DUA, J. A. Um sopro de destrui��o: pensamento pol�tico e cr�tica ambiental no Brasilescravista (1786-1888). Rio de Janeiro: Zahar, 2002 (adaptado).Descrevendo a posi��o dos cr�ticos ambientais brasileiros dos s�culos XVIII e XIX, o autor demonstra que, via de regra, eles viam o meio natural como','OFICIAL','A	ferramenta essencial para o avan�o da na��o. ','B d�diva divina para o desenvolvimento industrial. ','C paisagem privilegiada para a valoriza��o fundi�ria.','D	OLPLWDomR WRSRJUi�FD SDUD D SURPRomR GD XUEDQL]DomR ','E	obst�culo clim�tico para o estabelecimento da civiliza��o.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','2 FRURQHOLVPR HUD IUXWR GH DOWHUDomR QD UHODomR GH IRUoDV HQWUH RV SURSULHWiULRV UXUDLV H R JRYHUQR  H VLJQL�FDYD R  fortalecimento do poder do Estado antes que o predom�nio do coronel. Nessa concep��o, o coronelismo �, ent�o, um sistema pol�tico nacional, com base em barganhas entre o governo e os coron�is. O coronel tem o controle dos cargos p�blicos, desde o delegado de pol�cia at� a professora prim�ria. O coronel hipoteca seu apoio ao governo, sobretudo na forma de voto.CARVALHO, J. M. Pontos e bordados: escritos de hist�ria pol�tica. Belo Horizonte: Editora UFMG, 1998 (adaptado).No contexto da Primeira Rep�blica no Brasil, as rela��es pol�ticas descritas baseavam-se na','OFICIAL','A	coa��o das mil�cias locais.','B	estagna��o da din�mica urbana.','C	valoriza��o do proselitismo partid�rio. ','D dissemina��o de pr�ticas clientelistas.','E centraliza��o de decis�es administrativas.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Dessaliniza��o das �guasCapacidade total de dessaliniza��o das �guas salobras ou salinas (por pa�s em metros c�bicos por dia)EspanhaJap�o1 054 2742 588 658Estados Unidos5 653 941Em irados �rabes Unidos6 228 017Ar�bia Saudita6 879 869Kuwait2 111 558Capacidade instalada (m �/dia):5 001 a 50 00050 001 a 500 000500 001 a 1 000 000acim a de 1 000 000EUA. Relat�rio da Academia Nacional de Ci�ncias, 2008 (adaptado).Conforme a an�lise do documento cartogr�fico, a �rea de concentra��o das usinas de dessaliniza��o � explicada pelo(a)','OFICIAL','A	pioneirismo tecnol�gico. ','B condi��o hidropedol�gica. ','C escassez de �gua pot�vel.','D efeito das mudan�as clim�ticas.','E busca da sustentabilidade ambiental.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0',' Vi os homens sumirem-se numa grande tristeza. Os melhores cansaram-se das suas obras. Proclamou-se uma doutrina e com ela circulou uma cren�a: Tudo � oco, tudo � igual, tudo passou! O nosso trabalho foi in�til; o nosso vinho tornou- se veneno; o mau olhado amareleceu-nos os campos e os cora��es. Secamos de todo, e se ca�sse fogo em cima de n�s, as nossas cinzas voariam em p�. Sim; cansamos o pr�prio fogo. Todas as fontes secaram para n�s, e o mar retirou-se. Todos os solos se querem abrir, mas os abismos n�o nos querem tragar!NIETZSCHE, F. Assim falou Zaratustra. Rio de Janeiro: Ediouro, 1977.O texto exprime uma constru��o aleg�rica, que traduz um entendimento da doutrina niilista, uma vez que','OFICIAL','A	refor�a a liberdade do cidad�o. ','B desvela os valores do cotidiano. ','C exorta as rela��es de produ��o. ','D destaca a decad�ncia da cultura.','E DPSOL�FD R VHQWLPHQWR GH DQVLHGDGH |D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Pesca industrial provoca destrui��o na �fricaO	s�bito	desaparecimento	do	bacalhau	dosJUDQGHV FDUGXPHV GD 7HUUD 1RYD  QR �QDO GR VpFXOR ;; - o que ningu�m havia previsto -, teve o efeito de um eletrochoque planet�rio. Lan�ada pelos bascos no s�culo XV, a pesca e depois a sobrepesca desse grande peixe de �gua fria levaram ao impens�vel. Ao Canad� o bacalhau nunca mais voltou. E o que ocorreu no Atl�ntico Norte est� acontecendo em outros mares. Os maiores navios do mundo seguem agora em dire��o ao sul, at� os limites da Ant�rtida, para competir pelos estoques remanescentes.MORA, J. S. Dispon�vel em: www.diplomatique.com.br. Acesso em: 14 jan. 2014.O problema exposto no texto jornal�stico relaciona-se �','OFICIAL','A	insustentabilidade do modelo de produ��o e consumo. ','B fragilidade ecol�gica de ecossistemas costeiros.','C inviabilidade comercial dos produtos marinhos. ','D mudan�a natural nos oceanos e mares.','E vulnerabilidade social de �reas pobres.|A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A mundializa��o introduz o aumento da produtividade do trabalho sem acumula��o de capital, justamente pelo car�ter divis�vel da forma t�cnica molecular-digital do que resulta a perman�ncia da m� distribui��o daUHQGD   H[HPSOL�FDQGR  PDLV  XPD  YH]   RV  YHQGHGRUHV  de refrigerantes �s portas dos est�dios viram sua produtividade aumentada gra�as ao just in time dos fabricantes e distribuidores de bebidas, mas para realizar o valor de tais mercadorias, a forma do trabalho dos vendedores � a mais primitiva. Combinam- se, pois, acumula��o molecular-digital com o puro uso da for�a de trabalho.OLIVEIRA, F. Cr�tica � raz�o dualista e o ornitorrinco. Campinas: Boitempo, 2003.Os aspectos destacados no texto afetam diretamente quest�es como emprego e renda, sendo poss�vel explicar essas transforma��es pelo(a)','OFICIAL','A	crise banc�ria e o fortalecimento do capital industrial.','B	inova��o toyotista e a regulariza��o do trabalho formal.','C LPSDFWR  GD  WHFQRORJLD  H  DV  PRGL�FDo}HV  QD estrutura produtiva.','D	emerg�ncia da globaliza��o e a expans�o do setor secund�rio.','E	diminui��o do tempo de trabalho e a necessidade de diploma superior.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Ser moderno � encontrar-se em um ambiente que promete aventura, poder, alegria, crescimento, autotransforma��o e transforma��o das coisas em redor - mas ao mesmo tempo amea�a destruir tudo o que temos, tudo o que sabemos, tudo o que somos. A experi�ncia ambiental da modernidade anula todas asIURQWHLUDV JHRJUi�FDV H UDFLDLV  GH FODVVH H QDFLRQDOLGDGH   nesse sentido, pode-se dizer que a modernidade une a esp�cie humana. Por�m, � uma unidade paradoxal, uma unidade de desunidade.BERMAN, M. Tudo que � s�lido desmancha no ar: a aventura da modernidade.S�o Paulo: Cia. das Letras, 1986 (adaptado).O texto apresenta uma interpreta��o da modernidade que a caracteriza como um(a)','OFICIAL','A	din�mica social contradit�ria. ','B intera��o coletiva harm�nica. ','C fen�meno econ�mico est�vel.','D sistema internacional decadente. ','E processo hist�rico homogeneizador.|A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','N�o estou mais pensando como costumava pensar. Percebo isso de modo mais acentuado quando estou lendo. Mergulhar num livro, ou num longo artigo, costumava ser f�cil. Isso raramente ocorre atualmente. Agora minha aten��o come�a a divagar depois de duas ou tr�s p�ginas. Creio que sei o que est� acontecendo. Por mais de uma d�cada venho passando mais tempo on-line, procurando e surfando e algumas vezes acrescentando informa��o � grande biblioteca da internet. A internet tem sido uma d�diva para um escritor como eu. Pesquisas que antes exigiam dias de procura em jornais ou na biblioteca agora podem ser feitas em minutos. Como disse o te�rico da comunica��o Marshall McLuhan nos anos 60, a m�dia n�o � apenas um canal passivo para o tr�fego de informa��o. Ela fornece a mat�ria, mas tamb�m molda o processo de pensamento. E o que a net parece fazer � pulverizar minha capacidade de concentra��o e contempla��o.CARR, N. Is Google making us stupid? Dispon�vel em: www.theatlantic.com.Acesso em: 17 fev. 2013 (adaptado).Em rela��o � internet, a perspectiva defendida pelo autor ressalta um paradoxo que se caracteriza por','OFICIAL','A	DVVRFLDU  XPD  H[SHULrQFLD  VXSHU�FLDO  j  DEXQGkQFLD  de informa��es.','B condicionar uma capacidade individual � desorganiza��o da rede.','C	agregar uma tend�ncia contempor�nea � acelera��o do tempo.','D	aproximar uma m�dia inovadora � passividade da recep��o.','E	equiparar uma ferramenta digital � tecnologia anal�gica.|A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Uma scena franco-brazileira: "franco" - pelo local e os personagens, o local que � Paris e os personagens que s�o pess�as do povo da grande capital; "brazileira" pelo que ahi se est� bebendo: caf� do Brazil. O Lettreiro diz a verdade apregoando que esse � o melhor de todos os caf�s. (Essa p�gina foi desenhada especialmente para A Illustra��o Brazileira pelo Sr. Tofani, desenhista do Je Sais Tout.)A Illustra��o Brazileira, n. 2, 15 jun. 1909 (adaptado).A p�gina do peri�dico do in�cio do s�culo XX documenta um importante elemento da cultura francesa, que � revelador do papel do Brasil na economia mundial, indicado no seguinte aspecto:','OFICIAL','A	Prestador de servi�os gerais. ','B Exportador de bens industriais. ','C Importador de padr�es est�ticos. ','D Fornecedor de produtos agr�colas. ','E Formador de padr�es de consumo.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Participei de uma entrevista com o m�sico Renato Teixeira. Certa hora, algu�m pediu para listar as diferen�as entre a m�sica sertaneja antiga e a atual. A resposta dele surpreendeu a todos: "N�o h� diferen�a alguma. A m�sica caipira sempre foi a mesma. � uma m�sica que espelha a vida do homem no campo, e a m�sica n�o mente. O que mudou n�o foi a m�sica, mas a vida no campo". Faz todo sentido: a m�sica caipira de raiz exalava uma solid�o, um certo distanciamento do pa�s "moderno". Exigir o mesmo de uma m�sica feita hoje, num interior conectado, globalizado e rico como o que temos, � imposs�vel. Para o bem ou para o mal, a m�sica reflete seu pr�prio tempo.BARCINSKI, A. Mudou a m�sica ou mudaram os caipiras? Folha de S�o Paulo, 4 jun. 2012 (adaptado).A $QUEST�O cultural indicada no texto ressalta o seguinte aspecto socioecon�mico do atual campo brasileiro:','OFICIAL','A	Crescimento do sistema de produ��o extensiva. ','B Expans�o de atividades das novas ruralidades. ','C Persist�ncia de rela��es de trabalho compuls�rio. ','D Conten��o da pol�tica de subs�dios agr�colas.','E Fortalecimento do modelo de organiza��o cooperativa.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O n�mero de filhos por casal diminui rapidamente. Para a maioria dos economistas, isso representa um alerta para o futuro.Uma consequ�ncia socioecon�mica para os paises que vivenciam o fen�meno demogr�fico ilustrado � a diminui��o da','OFICIAL','A	oferta de m�o de obra nacional. ','B m�dia de expectativa de vida.','C disponibilidade de servi�os de sa�de. ','D despesa de natureza previdenci�ria.','E imigra��o de trabalhadores qXDOL� FDGRV |A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Em sua formula��o, o spray de pimenta cont�m porcentagens variadas de oleorresina de Capsicum, cujo princ�pio ativo � a capsaicina, e um solvente (um �lcool como etanol ou isopropanol). Em contato com os olhos, pele ou vias respirat�rias, a capsaicina causa um efeito inflemat�rio que gera uma sensa��o de dor e ardor, levando � cegueira tempor�ria. O processo�	desencadeado pela libera��o de neuropept�dios das termina��es nervosas.Quando uma pessoa � atingida com o spray de pimenta nos olhos ou na pele, a lavagem da regi�o atingida com �gua � ineficaz porque a ','OFICIAL','A	rea��o entre etanol e �gua libera calor, intensificando o ardor.','B	solubilidade do princ�pio ativo em �gua � muito baixa, dificultando a sua remo��o.','C	permeabilidade da �gua na pele � muito alta, n�o permitindo a remo��o do princ�pio ativo.','D	solubiliza��o do �leo em �gua causa um maior espalhamento al�m das �reas atingidas.','E	ard�ncia faz evaporar rapidamente a �gua, n�o permitindo que haja contato entre o �leo e o solvente.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A usina de Itaipu � uma das maiores hidrel�tricas do mundo em gera��o de energia. Com 20 unidades geradoras e 14 000 MW de pot�ncia total instalada, apresenta uma queda de 118,4 m e vaz�o nominal de 690	m3/s por unidade geradora. O c�lculo da pot�ncia te�rica leva em conta a altura da massa de �gua represada pela barragem, a gravidade local (10 m/s2) e a densidade da �gua (1 000 kg/m3). A diferen�a entre a pot�ncia te�rica e a instalada � a pot�ncia n�o aproveitada.Qual � a pot�ncia, em MW, n�o aproveitada em cada unidade geradora de Itaipu?','OFICIAL','A	0','B 1,18 ','C 116,96 ','D 816,96 ','E 13 183,04|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A coleta das fezes dos animais dom�sticos em sacolas pl�sticas e o seu descarte em lixeiras convencionais podem criar condi��es de degrada��o que geram produtos prejudiciais ao meio ambiente (Figura 1).   A Figura 2 ilustra o Projeto Park Spark, desenvolvido em Cambridge, MA (EUA), em que as fezes dos animais dom�sticos s�o recolhidas em sacolas biodegrad�veis e jogadas em um biodigestor instalado em parques p�blicos; e os produtos s�o utilizados em equipamentos no pr�prio parque.Uma inova��o desse projeto � possibilitar o(a)','OFICIAL','A	queima de g�s metano.','B	armazenamento de g�s carb�nico. ','C decomposi��o aer�bica das fezes.','D uso mais eficiente de combust�veis f�sseis','E fixa��o de carbono em mol�culas org�nicas. |A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Uma ambul�ncia A em movimento ret�lineo e uniforme aproxima-se de um observador O, em repouso. A sirene emite um som de frequ�ncia constante fA. O desenho ilustra as frentes de onda do som emitido pela ambul�ncia.2 O observador possui um detector que consegue registrar, no esbo�o de um gr�fico, a frequencia da onda sonoradetectada em fun��o do tempo fO(t), antes e depois da passagem da ambul�ncia por ele.Qual esbolo gr�fico representa a frequ�ncia fO(t) detectada pelo observador?','OFICIAL','A','B','C','D','E|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O benzeno, um importante solvente para a ind�stria qu�mica, � obtido industrialmente pela destila��o do petr�leo. Contudo, tamb�m pode ser sintetizado pela trimeriza��o do acetileno catalisada por ferro met�lico sob altas temperaturas, conforme a equa��o qu�mica:3 C2H2 (g)	C6H6 (l)A energia envolvida nesse processo pode ser calculada indiretamente pela varia��o de entalpia das rea��es de combust�o das subst�ncias participantes, nas mesmas condi��es experimentais:A varia��o de entalpia do processo de trimeriza��o, em kcal, para a forma��o de um mol de benzeno � mais pr�xima de','OFICIAL','A	-1 090.','B -150. ','C -50. ','D +157.','E +470.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Em meados de 2003, mais de 20 pessoas morreram no Brasil ap�s terem ingerido uma suspens�o de sulfato de b�rio utilizada como contraste em exames radiol�gicos. O sulfato de b�rio � um s�lido pouqu�ssimo sol�vel em �gua, que n�o se dissolve mesmo na presen�a de �cidos. As mortes ocorreram porque um laborat�rio farmac�utico forneceu o produto contaminado com carbonato de b�rio, que � sol�vel em meio �cido. Um simples teste para verificar a exist�ncia de �ons b�rio sol�veis poderia ter evitado a trag�dia. Esse teste consiste em tratar a amostra com solu��oaquosa de HCI e, ap�s filtrar paara separar os compostos insol�veis de b�rio, adiciona-se solu��o aquosa de H2SO4 sobre o filtrado e observa-se por 30 min.A presen�a de �ons b�rio sol�veis na amostra � indicada pela','OFICIAL','A	libera��o de calor.','B	altera��o da cor para rosa.','C	precipita��o de um s�lido branco. ','D forma��o de g�s hidrog�nio.','E volatiliza��o de g�s cloro.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Os ferom�nios s�o subst�ncias utilizadas na comunica��o entre indiv�duos de uma esp�cie. O primeiro ferom�nio isolado de um inseto foi o bombicol, subst�ncia produzida pela mariposa do bicho-da-seda.O HBombicolO uso de ferom�nios em a��es de controle de insetos-praga est� de acordo com o modelo preconizado para a agricultura do futuro. S�o agentes altamente especificos e seus compostos qu�micos podem ser empregados em determinados cultivos, conforme ilustrado no quadro.Considerando essas estruturas qu�micas, o tipo de estereoisomeria apresentada pelo bombicol � tamb�m apresentada pelo ferom�nio utilizado no controle do inseto','OFICIAL','A	Sitophilus spp. ','B Migdolus fryanus. ','C Anthonomus rubi. ','D Grapholita molesta.','E Scrobipalpuloides absoluta.|E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O esquema representa, de maneira simplificada, o processo de produ��o de etanol utilizando milho como mat�ria-prima.A etapa de hidr�lise na produ��o de etanol a partir do milho � fundamental para que','OFICIAL','A	a glicose seja convertida em sacarose. ','B as enzimas dessa planta sejam ativadas.','C a macera��o favore�a a solubiliza��o em �gua.','D	o amido seja transformado em substratos utiliz�veis pela levedura.','E	os gr�os com diferentes composi��es qu�micas sejam padronizados.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Durante a primeira fase do projeto de uma usina de gera��o de energia el�trica, os engenheiros da equipe de avalia��o de impactos ambientais procuram saber se esse projeto est� de acordo com as normas ambientais. A nova planta estar� localizada � beira de um rio, cuja temperatura m�dia da �gua � de 25 �C, e usar� a sua �gua somente para refrigera��o. O projeto pretende que a usina opere com 1,0 MW de pot�ncia el�trica e, em raz�o de restri��es t�cnicas, o dobro dessa pot�ncia ser� dissipada por seu sistema de arrefecimento, na forma de calor. Para atender a resolu��o n�mero 430, de 13 de maio de 2011, do Conselho Nacional do Meio Ambiente, com uma ampla margem de seguran�a, os engenheiros determinaram que a �gua s� poder� ser devolvida ao rio com um aumento de temperatura de, no m�ximo, 3 �C em rela��o � temperatura da �gua do rio captada pelo sistema de arrefecimento. Considere o calor especifico da �gua igual a 4 kJ/(kg �C).Para atender essa determina��o, o valor m�nimo do fluxo de �gua, em kg/s, para a refrigera��o da usina deve ser mais pr�ximo de','OFICIAL','A	42. ','B 84. ','C 167. ','D 250. ','E 500.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A figura 1 apresenta o gr�fico da intensidade, em decib�is (dB), da onda sonora emitida por um alto-falante, que est� em repouso, e medida por um microfone em fun��o da frequ�ncia da onda para diferentes dist�ncias: 3 mm, 25 mm, 51 mm e 60 mm. A Figura 2 apresenta um diagrama com a indica��o das diversas faixas do espectro de frequ�ncia sonora para o modelo de alto-falante utilizado neste experimento.Relacionando as informa��es presentes nas figuras 1 e 2, como a intensidade sonora percebida � afetada pelo aumento da dist�ncia do microfone ao alto-falante?','OFICIAL','A	Aumenta na faixa das frequ�ncias m�dias. ','B Diminui na faixa das frequ�ncias agudas. ','C Diminui na faixa das frequ�ncias graves.','D Aumenta na faixa das frequ�ncias m�dias altas. ','E Aumenta na faixa das frequ�ncias m�dias baixas.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','As prote�nas de uma c�lula eucari�tica possuem pept�deos sinais, que s�o sequ�ncias de amino�cidos respons�veis pelo seu endere�amento para as diferentes organelas, de acordo com suas fun��es. Um pesquisador desenvolveu uma nanopart�cula capaz de carregar prote�nas para dentro de tipos celulares espec�ficos. Agora ele quer saber se uma nanopart�cula carregada com uma prote�na bloqueadora do ciclo de Krebs in vitro � capaz de exercer sua atividade em uma c�lula cancerosa, podendo cortar o aporte energ�tico e destruir essas c�lulas.Ao escolher essa prote�na bloqueadora para carregar as nanopart�culas, o pesquisador deve levar em conta um pept�deo sinal de endere�amento para qual organela?','OFICIAL','A	N�cleo.','B	Mitoc�ndria. ','C Peroxissomo.','D Complexo golgiense.','E Ret�culo endoplasm�tico.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O morcego emite pulsos de curta dura��o de ondas ultrass�nicas, os quais voltam na forma de ecos ap�s atingirem objetos no ambiente, trazendo informa��es a respeito das suas dimens�es, suas localiza��es e dos seus poss�veis movimentos. Isso se d� em raz�o da sensibilidade do morcego em detectar o tempo gasto para os ecos voltarem, bem como das pequenas varia��es nas frequ�ncias e nas intensidades dos pulsos ultrass�nicos. Essas caracter�sticas lhe permitem ca�ar pequenas presas mesmo quando est�o em movimento em rela��o a si. Considere uma situa��o unidimensional em que uma mariposa se afasta, em movimento retil�neo e uniforme, de um morcego em repouso.A dist�ncia e velocidade da mariposa, na situa��o descrita, seriam detectadas pelo sistema de um morcego por quais altera��es nas caracter�sticas dos pulsos ultrass�nicos?','OFICIAL','A	Intensidade diminu�da, o tempo de retorno aumentado e a frequ�ncia percebida diminu�da.','B	Intensidade aumentada, o tempo de retorno diminu�do e a frequ�ncia percebida diminu�da.','C	Intensidade diminu�da, o tempo de retorno diminu�do e a frequ�ncia percebida aumentada.','D	Intensidade diminu�da, o tempo de retorno aumentado e a frequ�ncia percebida aumentada.','E	Intensidade aumentada, o tempo de retorno aumentado e a frequ�ncia percebida aumentada.|A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A minimiza��o do tempo e custo de uma rea��o qu�mica, bem como o aumento na sua taxa de convers�o, caracterizam a efici�ncia de um processi qu�mico. Como consequ�ncia, produtos podem chegar ao consumidor mais baratos. Um dos par�metros que mode a efici�ncia de uma rea��o qu�mica � o seu rendimento molar (R, em %), definida comoR =nproduto / nreagente limitante * 100em que n corresponde ao n�mero de mols. O metanol pode ser obtido pela rea��o entre brometo de metila e hidr�xido de s�dio, conforme a equa��o qu�mica:CH3Br + NaOH ->	CH3OH + NaBrAs massas molares (em g/mol) desses elementos s�o: H = 1; C = 12; O = 16; Na = 23; Br = 80.O rendimento molar da rea��o, em que 32 g de metanol foram obtidos a partir de 142,5 g de brometo de metila e 80 g de hidr�xido de s�dio, � mais pr�ximo de','OFICIAL','A	22%. ','B 40%. ','C 50%. ','D 67%. ','E 75%.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Por apresentar significativa resistividade el�trica, o grafite pode ser utilizado para simular resistores el�tricos em circuitos desenhados no papel, com o uso de l�pis e lapiseiras. Dependendo da espessura e do comprimento das linhas desenhadas, � poss�vel determinar a resist�ncia el�trica de cada tra�ado produzido. No esquema foram utilizados tr�s tipos de l�pis diferentes (2H, HB e 6B) para efetuar tr�s tra�ados distintos.Munido dessas informa��es, um estudante pegou uma folha de papel e fez o desenho de um sorvete de casquinha utilizando-se desses tra�ados. Os valores encontrados nesse experimento, para as resist�ncias el�tricas (R), medidas com o aux�lio de um ohm�metro ligado nas extremidades das resist�ncias, s�o mostrados na figura. Verificou-se que os resistores obedeciam � Lei de Ohm.Na sequ�ncia, conectou o ohm�metro nos terminaisA e B do desenho e, em seguida, conectou-o nos terminaisB e C, anotando as leituras RAB e RBC, respectivamente.Ao estabelecer a raz�oR AB, qual resultado o estudanteobteve?','OFICIAL','A 1','B 4/7','C	10/27','D	4/81','E	4/81|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O carv�o ativado � um material que possui elevado teor de carbono, sendo muito utilizado para a remo��o de compostos org�nicos vol�teis do meio, como o benzeno. Para a remo��o desses compostos, utiliza-se a adsor��o. Esse fen�meno ocorre por meio de intera��es do tipo intermoleculares entre a superf�cie do carv�o (adsorvente) e o benzeno (adsorvato, subst�ncia adsorvida).No caso apresentado, entre o adsorvente e a subst�ncia adsorvida ocorre a forma��o de:','OFICIAL','A	Liga��es dissulfeto. ','B Liga��es covalentes. ','C Liga��es de hidrog�nio.','D Intera��es dipolo induzido - dipolo induzido.','E Intera��es dipolo permanente - dipolo permanente.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Um pesquisador investigou o papel da preda��o por peixes na densidade e tamanho das presas, como poss�vel controle de popula��es de esp�cies ex�ticas em cost�es rochosos. No experimento colocou uma tela sobre uma �rea da comunidade, impedindo o acesso dos peixes ao alimento, e comparou o resultado com uma �rea adjacente na qual os peixes tinham acesso livre. O quadro apresenta os resultados encontrados ap�s 15 dias de experimento.O pesquisador concluiu corretamente que os peixes controlam a densidade dos(as)','OFICIAL','A	algas, estimulando seu crescimento.','B	cracas, predando especialmente animais pequenos. ','C mexilh�es, predando especialmente animais pequenos.','D	quatro esp�cies testadas, predando indiv�duos pequenos.','E	asc�dias, apesar de n�o representarem os menores organismos.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Ao percorrer o trajeto de uma cadeia alimentar, o carbono, elemento essencial e majorit�rio da mat�ria org�nica que comp�e os indiv�duos, ora se encontra em sua forma inorg�nica, ora se encontra em sua forma org�nica. Em uma cadeia alimentar composta por fitopl�ncton, zoopl�ncton, molusco, crust�ceos e peixes ocorre a transi��o desse elemento da forma inorg�nica para a org�nica.Em qual grupo de organismos ocorre essa transi��o?','OFICIAL','A	Fitopl�ncton. ','B Zoopl�ncton. ','C Moluscos.','D Crust�ceos. ','E Peixes.|A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Dois ve�culos que trafegam com velocidade constante em uma estrada, na mesma dire��o e sentido, devem manter entre si uma dist�ncia m�nima. Isso porque o movimento de um ve�culo, at� que ele pare totalmente, ocorre em duas etapas, a partir do momento em que o motorista detecta um problema que exige uma freada brusca. A primeira etapa � associada�	dist�ncia que o ve�culo percorre entre o intervalo de tempo da detec��o do problema e o acionamento dos freios. J� a segunda se relaciona com a dist�ncia que o autom�vel percorre enquanto os freios agem com desacelera��o constante.Considerando a situa��o descrita, qual esbo�o gr�fico representa a velocidade do autom�vel em rela��o � dist�ncia percorrida at� parar totalmente?','OFICIAL','A','B','C','D','E|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','TEXTO IBioc�lulas combust�veis s�o uma alternativa tecnol�gica para substitui��o das baterias convencionais. Em uma bioc�lula microbiol�gica, bact�rias catalisam rea��es de oxida��o de substratos org�nicos. Liberam el�trons produzidos na respira��o celular para um eletrodo, onde fluem por um circuito externo at� o c�todo do sistema, produzindo corrente el�trica. Uma rea��o t�pica que ocorre em bioc�lulas microbiol�gicas utiliza o acetato como substrato.TEXTO IIEm sistemas bioeletroqu�micos, os potenciais padr�o (E�) apresentam valores caracter�sticos. Para as bioc�lulas de acetato, considere as seguintes semirrea��es de redu��o e seus respectivos potenciais:Nessas condi��es, qual � o n�mero m�nimo de bioc�lulas de acetato, ligadas em s�rie, necess�rias para se obter uma diferen�a de potencial de 4,4 V?','OFICIAL','A	3','B 4 ','C 6 ','D 9','E 15|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A forma��o de co�gulos sangu�neos em veias e art�rias � um dos fatores respons�veis pela ocorr�ncia de doen�as cardiovasculares, como varizes, infarto e acidentes vasculares cerebrais. A preven��o e o tratamento dessas doen�as podem ser feitos com drogas anticoagulantes. A ind�stria farmac�utica estimula a pesquisa de toxinas animais com essa propriedade.Considerando as adapta��es relacionadas aos h�bitos alimentares, os animais adequados ao prop�sito dessas pesquisas s�o os(as)','OFICIAL','A	moluscos fit�fagos ','B moscas sapr�fagas. ','C p�ssaros carn�voros. ','D morcegos frug�voros.','E mosquitos hemat�fagos.|E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A inven��o e o acoplamento entre engrenagens revolucionaram a ci�ncia na �poca e propiciaram a inven��o de v�rias tecnologias, como os rel�gios. Ao construir um pequeno cron�metro, um relojoeiro usa o sistema de engrenagens mostrado. De acordo com a figura, um motor � ligado ao eixo e movimenta as engrenagens fazendo o ponteiro girar. A frequ�ncia do motor � de 18 RPM, e o n�mero de dentes das engrenagens est� apresentado no quadro.A frequ�ncia de giro do ponteiro, em RPM, �','OFICIAL','A	1. ','B 2. ','C 4.','D 81. ','E 162.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Primeiro, em rela��o �quilo a que chamamos �gua, quando congela, parece-nos estar a olhar para algo que se tornou pedra ou terra, mas quando derrete e se dispersa, esta torna-se bafo e ar; o ar, quando � queimado, torna-se fogo; e, inversamente, o fogo, quando se contrai e se extingue, regressa � forma do ar; o ar, novamente concentrado e contra�do, torna-se nuvem e nevoeiro, mas, a partir destes estados, se for ainda mais comprimido, torna-se �gua corrente, e de �gua torna-se novamente terra e pedras; e deste modo, como nos parece, d�o gera��o uns aos outros de forma c�clica.PLAT�O. Timeu-Cr�tias. Coimbra: CECH, 2011.    Do ponto de vista da ci�ncia moderna, os "quatro elementos" descritos por Plat�o correspondem, na verdade, �s fases s�lida, l�quida, gasosa e plasma da mat�ria. As transi��es entre elas s�o hoje entendidas como consequ�ncias macrosc�picas de transforma��es sofridas pela mat�ria em escala microsc�pica.Excetuando-se a fase de plasma, essas transforma��es sofridas pela mat�ria, em n�vel microsc�pico, est�o associadas a uma','OFICIAL','A	troca de �tomos entre as diferentes mol�culas do material.','B	transmuta��o nuclear dos elementos qu�micos do material.','C	redistribui��o de pr�tons entre os diferentes �tomos do material.','D	mudan�a na estrutura espacial formada pelos diferentes constituintes do material.','E	altera��o nas propor��es dos diferentes is�topos de cada elemento presente no material.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Para cada litro de etanol produzido em uma ind�stria de cana- de-a��car s�o gerados cerca de 18 L de vinha�a que � utilizada na irriga��o das planta��es de cana- de -a��car, j� que cont�m teores m�dios de nutrientes N, P e K iguais a 357 mg/L, 60 mg/L e 2 034 mg/L, respectivamente.SILVA, M. A. S.; GRIEBELER, N. P.; BORGES, L. C. Uso de vinha�a e impactos nas propriedades do solo e len�ol fre�tico. Revista Brasileira de Engenharia Agr�cola e Ambiental, n. 1, 2007 (adaptado).Na produ��o de 27 000 L de etanol, a quantidade total de f�sforo, em kg, dispon�vel na vinha�a ser� mais pr�xima de','OFICIAL','A	1.','B 29. ','C 60. ','D 170. ','E 1 000.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Recentemente um estudo feito em campos de trigo mostrou que n�veis elevados de di�xido de carbono na atmosfera prejudicam a absor��o de nitrato pelas plantas. Consequentemente, a qualidade nutricional desses alimentos pode diminuir � medida que os n�veis de di�xido de carbono na atmosfera atingirem as estimativas para as pr�ximas d�cadas.BLOOM, A. J. et al. Nitrate assimilation is inhibited by elevated CO2 LQ �HOG JURZQ ZKHDW   Nature Climate Change, n. 4, abr. 2014 (adaptado).Nesse contexto, a qualidade nutricional do gr�o de trigo VHUi PRGL�FDGD SULPDULDPHQWH SHOD UHGXomR GH','OFICIAL','A	amido. ','B frutose. ','C lip�deos. ','D celulose. ','E prote�nas.|E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Pesquisadores recuperaram DNA de ossos de mamute (Mammuthus primigenius) encontrados na Sib�ria, que tiveram sua idade de cerca de 28 mil anos confirmada pela t�cnica do carbono-14    FAPESP. DNA de mamute � revelado. Dispon�vel em: http://agencia.fapesp.br.Acesso em: 13 ago. 2012 (adaptado).A t�cnica de data��o apresentada no texto s� � poss�vel devido �','OFICIAL','A	propor��o conhecida entre carbono-14 e carbono-12 na atmosfera ao longo dos anos.','B	decomposi��o de todo o carbono-12 presente no organismo ap�s a morte.','C fixa��o maior do carbono-14 nos tercidos de organimos ap�s a morte.','D	emiss�o de carbono-12 pelos tecidos de organismos ap�s a morte.','E	transforma��o do carbono-12 em carbono-14 ao longo dos anos.|A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A vegeta��o apresenta adapta��es ao ambiente, como plantas arb�reas e arbustivas com ra�zes que se expandem horizontalmente, permitindo forte ancoragem no substrato lamacento; ra�zes que se expandem verticalmente, por causa da baixa oxigena��o do substrato; folhas que t�m gl�ndulas para eliminar o excesso de sais; folhas que podem apresentar cut�cula espessa para reduzir a perda de �gua por evapora��o.As caracter�sticas descritas referem-se a plantas adaptadas ao bioma:','OFICIAL','A	Cerrado. ','B Pampas. ','C Pantanal.','D Manguezal.','E Mata de Cocais.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Uma pessoa � respons�vel pela manuten��o de uma sauna �mida. Todos os dias cumpre o mesmo ritual: colhe folhas de capim-cidreira e algumas folhas de eucalipto. Em seguida, coloca as folhas na sa�da do vapor da sauna, aromatizando-a, conforme representado na figura.Qual processo de separa��o � respons�vel pela aromatiza��o promovida?','OFICIAL','A	Filtra��o simples. ','B Destila��o simples. ','C Extra��o por arraste.','D Sublima��o fracionada. ','E Decanta��o s�lido-l�quido.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Os ecossistemas degradados por intensa atividade agr�cola apresentam, geralmente, diminui��o de sua diversidade e perda de sua estabilidade. Nesse contexto, o uso integrado de �rvores aos sistemas agr�colas(sistemas agroflorestais) pode cumpri um papel inovador ao buscar a acelera��o do processo sucessional e, ao mesmo tempo, uma produ��o escalonada e diversificada.Essa � uma estrat�gia de concilia��o entre recupera��o ambiental e produ��o agr�cola, pois','OFICIAL','A	substitui gradativamente as esp�cies cultiv�veis por esp�cies arb�reas.','B	intensifica a fertiliza��o do solo com o uso de t�cnicas apropriadas e biocidas.','C	promove maior diversidade de vida no solo com oaumento da mat�ria org�nica.','D	favorece a dispers�o das sementes cultivadas pela fauna residente nas �reas florestais.','E	cria condi��es para o estabelecimento de esp�cies pioneiras com a diminui��o da insola��o sobre o solo.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Tr�s l�mpadas id�nticas foram ligadas no circuito esquematizado. A bateria apresenta resist�ncia interna desprez�vel, e os fios possuem resist�ncia nula. Um t�cnico fez uma an�lise do circuito para prever a corrente el�trica nos pontos:  , B, C, D e E; e rotulou essas correntes de IA, IB, IC, ID e IE, respectivamente.O t�cnico concluiu que as correntes que apresentam o mesmo valor s�o','OFICIAL','A	IA = IE e IC = ID.','B IA = IB = IE e IC = ID. ','C IA = IB, apenas.','D IA = IB = IE, apenas. ','E IC = IB, apenas.|A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A figura ilustra o movimento da seiva xil�mica em uma plantaMesmo que essa planta viesse a sofrer a��o cont�nua do vento e sua copa crescesse voltada para baixo, essa seiva continuaria naturalmente seu percurso.O que garante o transporte dessa seiva � a','OFICIAL','A	guta��o.','B gravidade. ','C respira��o. ','D fotoss�ntese. ','E transpira��o.|E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Nucle�filos(Nu) s�o bases de Lewis que reagem com haletos de alquila, por meio de uma rea��o chamada substitui��o nucleof�lica (SN), como mostrado no esquema:R-X + Nu 	R-Nu + X 	(R = grupo alquila e X = halog�nio)A rea��o de SN entre met�xido de s�dio (Nu  = CH3O ) e brometo de metila fornece um composto org�nico pertencente � fun��o','OFICIAL','A	�ter. ','B �ster. ','C �lcool. ','D haleto.','E hidrocarboneto.|A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O trilho de ar � um dispositivo utilizado em laborat�rios de f�sica para analisar movimentos em que corpos de prova (carrinhos) podem se mover com atrito desprez�vel. A figura ilustra um trilho horizontal com dois carrinhos (1 e 2) em que se realiza um experimento para obter a massa do carrinho 2. No instante em que o carrinho 1, de massa 150,0 g, passa a se mover com velocidade escalar constante, o carrinho 2 est� em repouso. No momento em que o carrinho 1 se choca com o carrinho 2, ambos passam a se movimentar juntos com velocidade escalar constante. Os sensores eletr�nicos distribu�dos ao longo do trilho determinam as posi��es e registram os instantes associados � passagem de cada carrinho, gerando os dados do quadro.Com base nos dados experimentais, o valor da massa do carrinho 2 � igual a','OFICIAL','A	50,0 g. ','B 250,0 g. ','C 300,0 g. ','D 450,0 g. ','E 600,0 g.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Ap�s seu desgaste completo, os pneus podem ser queimados para a gera��o de energia. Dentre os gases gerados na combust�o completa da borracha vulcanizada, alguns s�o poluentes e provocam a chuva �cida. Para evitar que escapem para a atmosfera, esses gases podem ser borbulhados em uma solu��o aquosa contendo uma subst�ncia adequada. Considere as informa��es das subst�ncias listadas no quadro.Subst�nciaEquil�brio em solu��o aquosaValor da constante de equil�brioDentre as subst�ncias listadas no quadro, aquela capaz de remover com maior efici�ncia os gases poluentes � o(a)','OFICIAL','A	fenol.','B piridina.','C metilamina.','D hidrogenofosfato de pot�ssio. ','E hidrogenosulfato de pot�ssio.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','V�rios m�todos s�o empregados para preven��o de infec��es por microrganismos. Dois desses m�todos utilizam microrganismos vivos e s�o eles: as vacinas atenuadas, constitu�das por pat�genos avirulentos, e os probi�ticos que cont�m bact�rias ben�ficas. Na figura s�o apresentados cinco diferentes mecanismos de exclus�o de pat�genos pela a��o dos probi�ticos no intestino de um animal.Qual mecanismo de a��o desses probi�ticos promove um efeito similar ao da vacina?','OFICIAL','A	5','B 4 ','C 3 ','D 2 ','E 1|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O Painel Intergovernamental de Mudan�as Clim�ticas (na sigla em ingl�s, IPCC) prev� que nas pr�ximas d�cadas o planeta passar� por mudan�as clim�ticas e prop�e estrat�gias de mitiga��o e adapta��o a elas. As estrat�gias de mitiga��o s�o direcionadas � causa dessas mudan�as, procurando reduzir a concentra��o de gases de efeito estufa na atmosfera. As estrat�gias de adapta��o, por sua vez, s�o direcionadas aos efeitos dessas mudan�as, procurando preparar os sistemas humanos �s mudan�as clim�ticas j� em andamento, de modo a reduzir seus efeitos negativos.IPCC, 2014. Climate Change 2014: synthesis report. Dispon�vel em: http://ar5-syr.ipcc.ch. Acesso em: 22 out. 2015 (adaptado).Considerando as informa��es do texto, qual a��o representa uma estrat�gia de adapta��o?','OFICIAL','A	Constru��o de usinas e�licas. ','B Tratamento de res�duos s�lidos.','C Aumento da efici�ncia dos ve�culos. ','D Ado��o de agricultura sustent�vel de baixo carbono. ','E Cria��o de diques de conten��o em regi�es costeiras.|E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A lipofilia � um dos fatores fundamentais para o planejamento de um f�rmaco. Ela mede o grau de afinidade que a subst�ncia tem com ambientes apolares, podendo ser avaliada por seu coeficiente de parti��o.Em rela��o ao coeficiente de parti��o da testosterona, as lipofilias dos compostos 1 e 2 s�o, respectivamente,','OFICIAL','A	menor e menor que a lipofilia da testosterona  ','B menor e maior que a lipofilia da testosterona ','C maior e menor que a lipofilia da testosterona.  ','D maior e maior que a lipofilia da testosterona. ','E menor e igual � lipofilia da testosterona.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Uma inven��o que significou um grande avan�o  tecnol�gico na Antiguidade, a polia composta ou a associa��o de polias, � atribu�da a Arquimedes (287 a.C. a 212 a.C.). O aparato consiste em associar uma s�rie de poliasm�veis a uma polia fixa. A figura exemplifica um arranjo poss�vel para esse aparato. � relatado que Arquimedes teria demonstrado para o rei Hier�o um outro arranjo desse aparato, movendo sozinho, sobre a areia da praia, um navio repleto de passageiros e cargas, algo que seria imposs�vel sem a participa��o de muitos homens. Suponha que a massa do navio era de 3 000 kg, que o coeficiente de atrito est�tico entre o navio e a areia era de 0,8 e que Arquimedes tenha puxado o navio com umafor�a F , paralela � dire��o do movimento e de m�dulo igual a 400 N. Considere os fios e as polias ideias, a acelera��o da gravidade igual a 10 m/s2 e que a superf�cie da praia � perfeitamente horizontal.O n�mero m�nimo de polias m�veis usadas, nessa situa��o, por Arquimedes foi','OFICIAL','A	3. ','B 6. ','C 7. ','D 8.','E 10.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O Brasil possui um grande n�mero de esp�cies distintas entre animais, vegetais e microrganismos envoltos em uma imensa complexidade e distribu�das em uma grande variedade de ecossistemas.O incremento da variabilidade ocorre em raz�o da permuta gen�tica, a qual propicia a troca de segmentos entre crom�tides n�o irm�s na meiose.Essa troca de segmentos � determinante na','OFICIAL','A	produ��o de indiv�duos mais f�rteis.','B	transmiss�o de novas caracter�sticas adquiridas. ','C recombina��o gen�tica na forma��o dos gametas. D ocorr�ncia de muta��es som�ticas nos descendentes.','E	varia��o do n�mero de cromossomos caracter�stico da esp�cie.|C','','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Num experimento, um professor deixa duas bandejas de mesma massa, uma de pl�stico e outra de alum�nio, sobre a mesa do laborat�rio. Ap�s algumas horas, ele pede aos alunos que avaliem a temperatura das duasbandejas, usando para isso o tato. Seus alunos afirmam, categoricamente, que a bandeja de alum�nio encontra-se numa temperatura mais baixa. Intrigado, ele prop�e uma segunda atividade, em que coloca um cubo de gelo sobre cada uma das bandejas, que est�o em equil�brio t�rmico com o ambiente, e os questiona em qual delas a taxa de derretimento do gelo ser� maior.O aluno que responder corretamente ao questionamento do professor dir� que o derretimento ocorrer�','OFICIAL','A	mais rapidamente na bandeja de alum�nio, pois ela tem uma maior condutividade t�rmica que a de pl�stico.','B	mais rapidamente na bandeja de pl�stico, pois ela tem inicialmente uma temperatura mais alta que a de alum�nio.','C	mais rapidamente na bandeja de pl�stico, pois ela tem uma maior capacidade t�rmica que a de alum�nio.','D	mais rapidamente na bandeja de alum�nio, pois ela tem um calor espec�fico menor que a de pl�stico.','E	com a mesma rapidez nas duas bandejas, pois apresentar�o a mesma varia��o de temperatura.|A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Os tensoativos s�o compostos capazes de interagir com subst�ncias polares e apolares. A parte i�nica dos tensoativos interage com subst�ncias polares, e a parte lipof�lica interage com as apolares. A estrutura org�nica de um tensoativo pode ser representada por:Ao adicionar um tensoativo sobre a �gua, suas mol�culas formam um arranjo ordenado.Esse arranjo � representado esquematicamente por:','OFICIAL','A','B','C','D','E|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Um experimento para comprovar a natureza ondulat�ria da radia��o de micro-ondas foi realizado da seguinte forma: anotou-se a frequ�ncia de opera��o de um forno de micro-ondas e, em seguida, retirou-se sua plataforma girat�ria. No seu lugar, colocou-se uma travessa refrat�ria com uma camada grossa de manteiga. Depois disso, o forno foi ligado por alguns segundos. Ao se retirar a travessa refrat�ria do forno, observou-se que havia tr�s pontos de manteiga derretida alinhados sobre toda a travessa. Parte da onda estacion�ria gerada no interior do forno � ilustrada na figura.De acordo com a figura, que posi��es correspondem a dois pontos consecutivos da manteiga derretida?','OFICIAL','A	I e III ','B I e V ','C II e III','D II e IV ','E II e V|A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Portadores	de	diabetes	insipidus	reclamam	daconfus�o feita pelos profissionais da sa�de quanto aos dois tipos de diabetes: mellitus e insipidus. Enquanto o primeiro tipo est� associado aos n�veis ou � a��o da insulina, o segundo n�o est� ligado � defici�ncia dessehorm�nio. O diabetes insipidus � caracterizado por um dist�rbio na produ��o ou no funcionamento do horm�nio antidiur�tico (na sigla em ingl�s, ADH), secretado pela neuro-hip�fise para controlar a reabsor��o de �gua pelos t�bulos renais.Tendo em vista o papel funcional do ADH, qual � um sintoma cl�ssico de um paciente acometido por diabetes insipidus?','OFICIAL','A	Alta taxa de glicose no sangue. ','B Aumento da press�o arterial. ','C Ganho de massa corporal.','D Anemia cr�nica. ','E Desidrata��o.|E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','','OFICIAL','A	o campo magn�tico gerado pela oscila��o das nanopart�culas � absorvido pelo tumor.','B	o campo magn�tico alternado faz as nanopart�culas girarem, transferindo calor por atrito.','C	as nanopart�culas interagem magneticamente com as c�lulas do corpo, transferindo calor.','D	o campo magn�tico alternado fornece calor para as nanopart�culas que o transfere �s c�lulas do corpo.','E	as nanopart�culas s�o aceleradas em um �nico sentido em raz�o da intera��o com o campo magn�tico, fazendo-as colidir com as c�lulas e transferir calor.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O aquecimento de um material por irradia��o com micro-ondas ocorre por causa da intera��o da onda eletromagn�tica com o dipolo el�trico da mol�cula. Um importante atributo do aquecimento por micro-ondas�	a absor��o direta da energia pelo material a ser aquecido. Assim, esse aquecimento � seletivo e depender�, principalmente, da constante diel�trica e da frequ�ncia de relaxa��o do material. O gr�fico mostra a taxa de aquecimento de cinco solventes sob irradia��o de micro-ondas.No gr�fico, qual solvente apresenta taxa m�dia de aquecimento mais pr�xima de zero, no intervalo de0 s a 40 s?','OFICIAL','A	H2O ','B CH3OH','C CH3CH2OH ','D CH3CH2CH2OH','E CH3CH2CH2CH2CH2CH3|E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Apesar da grande diversidade biol�gica, a hip�tese de que a vida na Terra tenha tido uma �nica origem comum � aceita pela comunidade cientifica.Uma evid�ncia que apoia essa hip�tese � a observa��o de processos biol�gicos comuns a todos os seres vivos atualmente existentes.Um exemplo de tal processo � o(a)','OFICIAL','A	desenvolvimento embrion�rio. ','B reprodu��o sexuada.','C respira��o aer�bica. ','D excre��o urin�ria. ','E s�ntese proteica.|E','|E');


